project_id = "wmefczrhnsqicikveuhz"

[functions.fit-scan-detect]
verify_jwt = false

[functions.mailerlite-subscribe]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false
