// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_products_default = defineTool({
  name: "list_products",
  title: "List Woolet products",
  description: "List Woolet eyewear products with model, width, bridge, and pre-order pricing (USD).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const products = [
      {
        id: "007",
        name: "Woolet 007 Round",
        shape: "Round",
        widthMm: 158,
        bridgeMm: 22,
        preOrderUsd: 133,
        regularUsd: 190,
        url: "https://woolet.co/en/products/007"
      },
      {
        id: "009",
        name: "Woolet 009 Square",
        shape: "Square",
        widthMm: 158,
        bridgeMm: 21,
        preOrderUsd: 133,
        regularUsd: 190,
        url: "https://woolet.co/en/products/009"
      },
      {
        id: "bespoke",
        name: "Woolet Bespoke",
        shape: "Made-to-measure (Aviator / Rectangle / Crown Panto / Round)",
        widthMm: "145\u2013172 (cut to face)",
        bridgeMm: "custom",
        preOrderUsd: 480,
        regularUsd: 480,
        url: "https://woolet.co/en/bespoke"
      }
    ];
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/recommend-fit.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var RECS = [
  {
    minFaceWidthMm: 150,
    maxFaceWidthMm: 158,
    recommendation: "Woolet 007 Round or 009 Square \u2014 both 158 mm front width. Try the Fit Wizard for a shape recommendation.",
    url: "https://woolet.co/en/fit"
  },
  {
    minFaceWidthMm: 159,
    maxFaceWidthMm: 172,
    recommendation: "Woolet Bespoke \u2014 cut to your exact face width (145\u2013172 mm).",
    url: "https://woolet.co/en/bespoke"
  }
];
var recommend_fit_default = defineTool2({
  name: "recommend_fit",
  title: "Recommend Woolet fit",
  description: "Recommend a Woolet model based on face width in millimetres (measured temple-to-temple). Wide faces only \u2014 150 mm and above.",
  inputSchema: {
    faceWidthMm: z.number().min(120).max(200).describe("Face width in millimetres, measured temple-to-temple.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ faceWidthMm }) => {
    if (faceWidthMm < 150) {
      return {
        content: [
          {
            type: "text",
            text: `Face width ${faceWidthMm} mm is narrower than Woolet's 150 mm minimum. Woolet is built for wide faces (155 mm+). Standard eyewear brands will fit better.`
          }
        ],
        structuredContent: { faceWidthMm, match: null }
      };
    }
    const match = RECS.find(
      (r) => faceWidthMm >= r.minFaceWidthMm && faceWidthMm <= r.maxFaceWidthMm
    );
    return {
      content: [
        {
          type: "text",
          text: match ? `${match.recommendation} (${match.url})` : `Face width ${faceWidthMm} mm exceeds Woolet Bespoke's 162 mm max. Contact support@woolet.co.`
        }
      ],
      structuredContent: { faceWidthMm, match: match ?? null }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "wmefczrhnsqicikveuhz";
var mcp_default = defineMcp({
  name: "woolet-mcp",
  title: "Woolet Eyewear",
  version: "0.1.0",
  instructions: "Tools for Woolet, an Italian acetate eyewear brand for wide faces (145\u2013172 mm). Use `list_products` to browse models 007, 009, and Bespoke. Use `recommend_fit` to suggest a model from a face width in millimetres.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, recommend_fit_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
